Daniel Sarabia, [20/04/2023 20:10]
q1 Custom Age --> 8 valores diferentes, 0 valores null, y sus valores son [2. 5. 3. 4. 6. 7. 8. 1.]
q2 Sex --> 2 valores diferentes, 0 valores null, y sus valores son [2. 1.]
q3 In what grade are you --> 5 valores diferentes, 0 valores null, y sus valores son [4. 2. 3. 5. 1.]
q6 How often went hungry --> 5 valores diferentes, 0 valores null, y sus valores son [1. 3. 2. 5. 4.]
q10 Fast food eating  --> 8 valores diferentes, 0 valores null, y sus valores son [1. 5. 2. 4. 3. 8. 6. 7.]
q15 Physically attacked --> 8 valores diferentes, 0 valores null, y sus valores son [1. 8. 2. 3. 4. 6. 5. 7.]
q16 Physical fighting --> 8 valores diferentes, 0 valores null, y sus valores son [1. 2. 3. 6. 4. 7. 8. 5.]
q17 Seriously injured --> 8 valores diferentes, 0 valores null, y sus valores son [1. 2. 3. 4. 8. 5. 6. 7.]
q18 Serious injury type  --> 8 valores diferentes, 0 valores null, y sus valores son [1. 2. 8. 4. 3. 6. 7. 5.]
q19 Serious injury cause --> 8 valores diferentes, 0 valores null, y sus valores son [1. 3. 8. 4. 7. 5. 2. 6.]
q22 Felt lonely --> 5 valores diferentes, 0 valores null, y sus valores son [2. 1. 3. 5. 4.]
q23 Could not sleep --> 5 valores diferentes, 0 valores null, y sus valores son [2. 4. 5. 1. 3.]
q24 Considered suicide --> 2 valores diferentes, 0 valores null, y sus valores son [2. 1.]
q25 Made a suicide plan --> 2 valores diferentes, 0 valores null, y sus valores son [2. 1.]
q26 Attempted suicide --> 5 valores diferentes, 0 valores null, y sus valores son [1. 2. 3. 4. 5.]
q27 Close friends --> 4 valores diferentes, 0 valores null, y sus valores son [4. 1. 3. 2.]
q28 Initiation of cigarette use --> 8 valores diferentes, 0 valores null, y sus valores son [1. 3. 2. 6. 5. 4. 7. 8.]
q29 Current cigarette use --> 7 valores diferentes, 0 valores null, y sus valores son [1. 3. 4. 2. 5. 6. 7.]
q30 Other tobacco use --> 7 valores diferentes, 0 valores null, y sus valores son [1. 3. 4. 6. 2. 5. 7.]
q31 Smoking cessation --> 4 valores diferentes, 0 valores null, y sus valores son [1. 2. 4. 3.]
q32 Smoking in their presence --> 5 valores diferentes, 0 valores null, y sus valores son [1. 5. 2. 3. 4.]
q33 Parental tobacco use --> 5 valores diferentes, 0 valores null, y sus valores son [1. 4. 2. 3. 5.]
q34 Initiation of alcohol use --> 8 valores diferentes, 0 valores null, y sus valores son [5. 1. 4. 2. 6. 3. 7. 8.]
q35 Current alcohol use --> 7 valores diferentes, 0 valores null, y sus valores son [1. 2. 3. 6. 4. 5. 7.]
q36 Drank 2+ drinks  --> 7 valores diferentes, 0 valores null, y sus valores son [1. 5. 4. 7. 2. 3. 6.]
q37 Source of alchohol --> 7 valores diferentes, 0 valores null, y sus valores son [1. 2. 7. 4. 5. 6. 3.]
q38 Really drunk --> 4 valores diferentes, 0 valores null, y sus valores son [1. 2. 4. 3.]
q39 Trouble from drinking --> 4 valores diferentes, 0 valores null, y sus valores son [1. 4. 2. 3.]
q40 Initiation of drug use --> 8 valores diferentes, 0 valores null, y sus valores son [1. 6. 5. 2. 4. 7. 3. 8.]
q41 Ever marijuana use --> 5 valores diferentes, 0 valores null, y sus valores son [1. 3. 2. 5. 4.]
q42 Current marijuana use  --> 5 valores diferentes, 0 valores null, y sus valores son [1. 3. 4. 2. 5.]
q43 Amphethamine or methamphetamine use --> 5 valores diferentes, 0 valores null, y sus valores son [1. 2. 5. 4. 3.]
q44 Ever sexual intercourse --> 2 valores diferentes, 0 valores null, y sus valores son [2. 1.]
q45 Age first had sex --> 8 valores diferentes, 0 valores null, y sus valores son [1. 5. 4. 2. 3. 6. 7. 8.]
q46 Number of sex partners --> 7 valores diferentes, 0 valores null, y sus valores son [1. 2. 4. 7. 3. 5. 6.]
q47 Condom use --> 3 valores diferentes, 0 valores null, y sus valores son [1. 2. 3.]
q48 Birth control used  --> 4 valores diferentes, 0 valores null, y sus valores son [1. 2. 3. 4.]
q49 Physical activity past 7 days --> 8 valores diferentes, 0 valores null, y sus valores son [3. 1. 5. 8. 2. 4. 6. 7.]
q50 Walk or bike to school --> 8 valores diferentes, 0 valores null, y sus valores son [1. 8. 4. 6. 3. 5. 2. 7.]
q51 PE attendance --> 6 valores diferentes, 0 valores null, y sus valores son [5. 6. 1. 3.
q52 Sitting activities --> 6 valores diferentes, 0 valores null, y sus valores son [1. 6. 2. 4. 3. 5.]
q53 Miss school no permission --> 5 valores diferentes, 0 valores null, y sus valores son [1. 3. 2. 4. 5.]
q54 Other students kind and helpful  --> 5 valores diferentes, 0 valores null, y sus valores son [4. 1. 3. 2. 5.]
q55 Parents check homework  --> 5 valores diferentes, 0 valores null, y sus valores son [2. 5. 1. 4. 3.]
q56 Parents understand problems --> 5 valores diferentes, 0 valores null, y sus valores son [1. 5. 3. 4. 2.]
q57 Parents know about free time --> 5 valores diferentes, 0 valores null, y sus valores son [5. 1. 4. 2. 3.]
q58 Parents go through their things --> 5 valores diferentes, 0 valores null, y sus valores son [1. 3. 2. 5. 4.
q61 Fruit consumption past 7 days --> 7 valores diferentes, 0 valores null, y sus valores son [2. 4. 7. 1. 5. 3. 6.]
q62 Vegetable consumption past 7 days --> 7 valores diferentes, 0 valores null, y sus valores son [2. 3. 5. 4. 6. 1. 7.]
q63 Soft drink consumption past 7 days  --> 7 valores diferentes, 0 valores null, y sus valores son [3. 5. 1. 7. 2. 4. 6.]
qn66 Bullied on school property in past 12 months --> 2 valores diferentes, 0 valores null, y sus valores son [2. 1.]
qn67 Bullied not on school property in past 12 months --> 2 valores diferentes, 0 valores null, y sus valores son [2. 1.]
qn69 Were underweight --> 2 valores diferentes, 0 valores null, y sus valores son [1. 2.]
LA COLUMNA OBJETIVO: qn68 Cyber bullied in past 12 months --> 2 valores diferentes, 0 valores null,  y sus valores son [2. 1.]